//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BaseHtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaseHtml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MenuLibrary.BaseHtml", typeof(BaseHtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;l-navbar&quot; id=&quot;nav-bar&quot;&gt;
        ///    &lt;nav class=&quot;nav&quot;&gt;
        ///        &lt;div&gt;
        ///            &lt;div class=&quot;nav_list nav_top&quot;&gt; 
        ///                &lt;a class=&quot;nav_link       &quot; asp-area=&quot;&quot; asp-controller=&quot;Map&quot;     asp-action=&quot;Map&quot;&gt;   &lt;i class=&quot;fas fa-map&quot;&gt;   &lt;/i&gt; &lt;span class=&quot;nav_name&quot;&gt;Map&lt;/span&gt; &lt;/a&gt;
        ///                &lt;a class=&quot;nav_link       &quot; asp-area=&quot;&quot; asp-controller=&quot;Home&quot;    asp-action=&quot;Docs&quot;&gt;  &lt;i class=&quot;fas fa-book&quot;&gt;  &lt;/i&gt; &lt;span class=&quot;nav_name&quot;&gt;Documentation&lt;/span&gt; &lt;/a&gt;
        ///                &lt;a class=&quot;nav_link       &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
    }
}
