//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MenuLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BaseHtml {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BaseHtml() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MenuLibrary.BaseHtml", typeof(BaseHtml).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;l-navbar&quot; id=&quot;nav-bar&quot;&gt;
        ///    &lt;nav class=&quot;nav&quot;&gt;
        ///        &lt;div&gt;
        ///            &lt;div class=&quot;nav_list nav_top&quot;&gt; 
        ///                {{MENU_LIST}}
        ///            &lt;/div&gt;
        ///            &lt;div class=&quot;nav_list nav_bottom&quot;&gt;
        ///                  &lt;a class=&quot;nav_link&quot;&gt;&lt;i id=&quot;header-toggle&quot; class=&quot;fas fa-angles-right&quot;&gt;&lt;/i&gt;&lt;span class=&quot;nav_name&quot;&gt;Shrink&lt;/span&gt;&lt;/a&gt;
        ///            &lt;/div&gt;
        ///        &lt;/div&gt;
        ///    &lt;/nav&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Please see documentation at https://docs.microsoft.com/aspnet/core/client-side/bundling-and-minification
        ///// for details on configuring this project to bundle and minify static web assets.
        ///
        ///// Write your JavaScript code.
        ///document.addEventListener(&quot;DOMContentLoaded&quot;, function (event) {
        ///
        ///    showNavbar()
        ///
        ///    const linkColor = document.querySelectorAll(&apos;.nav_link&apos;)
        ///
        ///    function colorLink() {
        ///        if (linkColor) {
        ///            linkColor.forEach(l =&gt; l.classList.remove(&apos;active&apos;))
        ///            t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///html {
        ///    font-size: 14px;
        ///}
        ///
        ///@media (min-width: 768px) {
        ///  html {
        ///    font-size: 16px;
        ///  }
        ///}
        ///
        ///:root {
        ///    --header-height: 2rem;
        ///    --nav-width: 68px;
        ///    --body-font: &apos;Nunito&apos;, sans-serif;
        ///    --normal-font-size: 1rem;
        ///    --z-fixed: 100;
        ///    --white-color: #838383;
        ///    --hover-color: #496f88;
        ///    --left-menu-background-color: #e9e7ef;
        ///    --left-menu-foreground-color: #838383;
        ///    --header-background-color: #9010c3;
        ///    --header-foreground-color: #e9e7ef;
        ///}
        ///
        ///.connected {
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Styles {
            get {
                return ResourceManager.GetString("Styles", resourceCulture);
            }
        }
    }
}
