name: Build/Test/Deploy
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  
jobs:
   deliver:
      uses: sfawcett123/workflows/.github/workflows/BUILD_TEST_DEPLOY.yml@main
      with:
        SONAR_KEY: sfawcett123_MenuLibrary
        SONAR_ORG: sfawcett
        APP_LOCN: MenuLibrary
        TEST_LOCN: MenuLibraryTest
      secrets:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         CODECOV: ${{ secrets.CODECOV }}
         NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
