name: NPM
on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  checks: write
  contents: write
  deployments: write
  issues: write
  packages: write
  pull-requests: write
  
jobs:
   deliver:
      uses: sfawcett123/workflows/.github/workflows/npm.yml@main
      secrets:
         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
